# Generated by Django 3.2.2 on 2021-05-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('middleinitial', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HEALTH.account')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('province', models.CharField(max_length=20)),
                ('barangay', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('maritalstatus', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widow/Widower')], max_length=1)),
            ],
            bases=('HEALTH.account',),
        ),
    ]
