# Generated by Django 3.2.2 on 2021-05-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True)),
                ('doctor', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=30)),
            ],
        ),
    ]
